"""normalized learning progress schema

Revision ID: 4e55865df366
Revises: 
Create Date: 2026-06-10 14:59:35.921156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4e55865df366'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.CheckConstraint("category IN ('streak', 'alphabet', 'practice', 'mastery')", name='ck_challenges_category'),
    sa.CheckConstraint('target > 0', name='ck_challenges_target_positive'),
    sa.CheckConstraint('xp_reward >= 0', name='ck_challenges_xp_reward_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_units_sort_order_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sort_order', name='uq_units_sort_order')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('email = lower(email)', name='ck_users_email_lowercase'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lessons',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('unit_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('youtube_id', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_lessons_sort_order_nonnegative'),
    sa.CheckConstraint('xp_reward >= 0', name='ck_lessons_xp_reward_nonnegative'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'sort_order', name='uq_lessons_unit_sort_order')
    )
    op.create_table('user_challenge_claims',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('challenge_id', sa.String(length=50), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('xp_earned >= 0', name='ck_user_challenge_claims_xp_nonnegative'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'challenge_id')
    )
    op.create_index('ix_user_challenge_claims_user_claimed_at', 'user_challenge_claims', ['user_id', 'claimed_at'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('initials', sa.String(length=10), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_progress_state',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('hearts', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('hearts >= 0', name='ck_user_progress_state_hearts_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('lesson_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('sign_word', sa.String(length=50), nullable=False),
    sa.Column('sign_description', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint("content_type IS NULL OR content_type IN ('letter', 'name')", name='ck_exercises_content_type'),
    sa.CheckConstraint("type IN ('demo', 'quiz', 'camera')", name='ck_exercises_type'),
    sa.CheckConstraint('sort_order >= 0', name='ck_exercises_sort_order_nonnegative'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'sort_order', name='uq_exercises_lesson_sort_order')
    )
    op.create_table('user_lesson_completions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.String(length=50), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('xp_earned >= 0', name='ck_user_lesson_completions_xp_nonnegative'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'lesson_id')
    )
    op.create_index('ix_user_lesson_completions_lesson_id', 'user_lesson_completions', ['lesson_id'], unique=False)
    op.create_index('ix_user_lesson_completions_user_completed_at', 'user_lesson_completions', ['user_id', 'completed_at'], unique=False)
    op.create_table('user_lesson_practice_days',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.String(length=50), nullable=False),
    sa.Column('practiced_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'lesson_id', 'practiced_on')
    )
    op.create_index('ix_user_lesson_practice_days_lesson_id', 'user_lesson_practice_days', ['lesson_id'], unique=False)
    op.create_index('ix_user_lesson_practice_days_user_date', 'user_lesson_practice_days', ['user_id', 'practiced_on'], unique=False)
    op.create_table('exercise_attempts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.String(length=50), nullable=False),
    sa.Column('attempt_type', sa.String(length=20), nullable=False),
    sa.Column('submitted_answer', sa.Text(), nullable=True),
    sa.Column('predicted_sign', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("attempt_type IN ('quiz', 'camera')", name='ck_exercise_attempts_type'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_exercise_attempts_confidence_range'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exercise_attempts_exercise_correct', 'exercise_attempts', ['exercise_id', 'is_correct'], unique=False)
    op.create_index('ix_exercise_attempts_user_camera_success', 'exercise_attempts', ['user_id', 'attempt_type', 'is_correct', 'exercise_id'], unique=False)
    op.create_index('ix_exercise_attempts_user_attempted_at', 'exercise_attempts', ['user_id', 'attempted_at'], unique=False)
    op.create_table('exercise_options',
    sa.Column('exercise_id', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_exercise_options_sort_order_nonnegative'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'value'),
    sa.UniqueConstraint('exercise_id', 'sort_order', name='uq_exercise_options_sort_order')
    )
    op.create_index('uq_exercise_options_one_correct', 'exercise_options', ['exercise_id'], unique=True, sqlite_where=sa.text('is_correct'), postgresql_where=sa.text('is_correct'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_exercise_options_one_correct', table_name='exercise_options')
    op.drop_table('exercise_options')
    op.drop_index('ix_exercise_attempts_user_attempted_at', table_name='exercise_attempts')
    op.drop_index('ix_exercise_attempts_user_camera_success', table_name='exercise_attempts')
    op.drop_index('ix_exercise_attempts_exercise_correct', table_name='exercise_attempts')
    op.drop_table('exercise_attempts')
    op.drop_index('ix_user_lesson_practice_days_user_date', table_name='user_lesson_practice_days')
    op.drop_index('ix_user_lesson_practice_days_lesson_id', table_name='user_lesson_practice_days')
    op.drop_table('user_lesson_practice_days')
    op.drop_index('ix_user_lesson_completions_user_completed_at', table_name='user_lesson_completions')
    op.drop_index('ix_user_lesson_completions_lesson_id', table_name='user_lesson_completions')
    op.drop_table('user_lesson_completions')
    op.drop_table('exercises')
    op.drop_table('user_progress_state')
    op.drop_table('user_profiles')
    op.drop_index('ix_user_challenge_claims_user_claimed_at', table_name='user_challenge_claims')
    op.drop_table('user_challenge_claims')
    op.drop_table('lessons')
    op.drop_table('users')
    op.drop_table('units')
    op.drop_table('challenges')
    # ### end Alembic commands ###
